name: Build Chrome Viction's Extension - Dev

on:
  push:
    branches:
      - development

env:
  APPLICATION: "viction"
  APP_TYPE: "chrome"
  ENVIRONMENT: "dev"
  AWS_REGION: "ap-southeast-1" # DON'T CHANGE, PLEASE
  WORKING_DIR: "." # CHANGE to "." on your repo
  DIR_TO_BUILD: "." # CHANGE to "." on your repo
  OUT_PATH: "apps/extension/build"
  OUT_FILE_NAME: "chrome-mv3-dev"
  PNPM_VERSION: "7"
  CMD_BUILD: "pnpm build:release"

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  set_vars:
    runs-on: [self-hosted, Linux]
    outputs:
      application: ${{ env.APPLICATION }}
      app_type: ${{ env.APP_TYPE }}
      aws_region: ${{ env.AWS_REGION }}
      aws_account_id: ${{ env.ENVIRONMENT == 'prd' && '249318657173' ||  '751062111139'  }}
      aws_role_assume_name: "c98-extension-artifact-${{ env.ENVIRONMENT == 'prd' && 'prd' ||  'stg'  }}"
      s3_bucket_name: "c98-extension-artifact-${{ env.ENVIRONMENT == 'prd' && 'prd' ||  'stg'  }}"
      working_dir: ${{ env.WORKING_DIR }}
      dir_to_build: ${{ env.DIR_TO_BUILD }}
      out_path: ${{ env.OUT_PATH }}
      out_file_name: ${{ env.OUT_FILE_NAME }}
      pnpm_version: ${{ env.PNPM_VERSION }}
      cmd_build: ${{ env.CMD_BUILD }}
    steps:
      - run: echo "Exposing ENV vars."

  pre-build:
    needs: [set_vars]
    uses: coin98/common-workflows/.github/workflows/ext-pre-build.yml@main
    with:
      app_name: ${{ needs.set_vars.outputs.application }}
      app_type: ${{ needs.set_vars.outputs.app_type }}
      download_url: "Not yet"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  build:
    needs: [set_vars, pre-build]
    uses: coin98/common-workflows/.github/workflows/build-extension.yaml@main
    with:
      app_name: ${{ needs.set_vars.outputs.application }}
      app_type: ${{ needs.set_vars.outputs.app_type }}
      aws_region: ${{ needs.set_vars.outputs.aws_region }}
      aws_account_id: ${{ needs.set_vars.outputs.aws_account_id }}
      aws_role_assume_name: ${{ needs.set_vars.outputs.aws_role_assume_name }}
      s3_bucket_name: ${{ needs.set_vars.outputs.s3_bucket_name }}
      working_dir: ${{ needs.set_vars.outputs.working_dir }}
      dir_to_build: ${{ needs.set_vars.outputs.dir_to_build }}
      out_path: ${{ needs.set_vars.outputs.out_path }}
      out_file_name: ${{ needs.set_vars.outputs.out_file_name }}
      pnpm_version: ${{ needs.set_vars.outputs.pnpm_version }}
      cmd_build: ${{ needs.set_vars.outputs.cmd_build }}

  post-build:
    needs: [set_vars, build]
    if: always()
    uses: coin98/common-workflows/.github/workflows/ext-post-build.yml@main
    with:
      app_name: ${{ needs.set_vars.outputs.application }}
      app_type: ${{ needs.set_vars.outputs.app_type }}
      build_status: ${{ needs.build.result }}
      download_url: ${{ needs.build.outputs.download_url }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}